# Generated by Django 4.0 on 2021-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('datecreate', models.DateField(auto_now_add=True)),
                ('dateupdate', models.DateField(auto_now=True)),
                ('projectname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('push_token', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('projects', models.ManyToManyField(related_name='users', to='app.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
